<a href="https://colab.research.google.com/github/DebjitHore/IntrotoTensorflowDeepLearningAI/blob/main/Tensorflow_2_0_Complete_Course_freecodecamp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Creating Tensors

In [37]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
%tensorflow_version 2.x

In [26]:
strings= tf.Variable('This is a string', tf.string)
number= tf.Variable('This is a string', tf.int16)
floatNumber= tf.Variable('This is a string', tf.float64)
# These are scalar variables

## Rank/Degree of Tensors

This term simply means the number of dimensions involved in the tensor. The above variables are tensors of rank 0, or scalars.

In [27]:
rank1_Tensor= tf.Variable(['Test', 'Okay'], tf.string)
rank2_Tensor= tf.Variable([['test', 'ok'],['jit', 'nya']], tf.string)

To determine the rank of a tensor use tf.rank

In [28]:
tf.rank(rank2_Tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [29]:
tf.rank(rank1_Tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=1>

The numpy value signifies the rank of the Tensor

## Shape of Tensors

The number of elements in a tensor is the product of the sizes of all its shapes. 

In [30]:
rank2_Tensor.shape

TensorShape([2, 2])

In [31]:
rank1_Tensor.shape

TensorShape([2])

## Changing shape of a Tensor

In [32]:
tensor1= tf.ones([1,2,3])
tensor2=tf.reshape(tensor1, [2,3,1])
tensor3= tf.reshape(tensor1, [3, -1]) #-1 tells the tensor to calculate the size of the dimension in that place

In [33]:
print(tensor1)

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)


In [34]:
print(tensor2)

tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)


In [35]:
print(tensor3)

tf.Tensor(
[[1. 1.]
 [1. 1.]
 [1. 1.]], shape=(3, 2), dtype=float32)


## Types of Tensors

* Constants
* Variables
* Placeholder
* SparseTensor

Except Variable, all of them are immutable.

## Evaluating Tensors
Gets the value of a Tensor. Since Tensors represent a partially complete computation we will sometimes need to run what's called a session to evaluate a tensor.

In [ ]:
with tf.Session() as sess:
  tensor.eval()   #tensor will be the name of the tensor

## Linear Regression using Tensorflow

### Setup and Imports

In [38]:
!pip install -q sklearn

In [39]:
%tensorflow_version 2.x

In [41]:
from __future__ import absolute_import, divison, print_function, unicode_literals
from IPython.display import clear_output
from six.moves import urllib

import tensorflow.compat.v2.feature_column as fc
import tensorflow as tf

SyntaxError: ignored